// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBmiKRBlOqt2Own2w_5iIMT4sMpsVHYU',
    appId: '1:928726006564:web:22a3b8da0210b32b8411b1',
    messagingSenderId: '928726006564',
    projectId: 'crud-hr08',
    authDomain: 'crud-hr08.firebaseapp.com',
    storageBucket: 'crud-hr08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5iea5qlj_PaSmFVeO_F9erYyLXCMwDdw',
    appId: '1:928726006564:android:6817805f20651e8e8411b1',
    messagingSenderId: '928726006564',
    projectId: 'crud-hr08',
    storageBucket: 'crud-hr08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqfp6Ad-__2qUnAmlVGs-nhs-WL-CfdG0',
    appId: '1:928726006564:ios:960bfcebeb26567a8411b1',
    messagingSenderId: '928726006564',
    projectId: 'crud-hr08',
    storageBucket: 'crud-hr08.appspot.com',
    androidClientId: '928726006564-9cl951lcbtrh3fa9vkne46gmbm6cvv5o.apps.googleusercontent.com',
    iosClientId: '928726006564-53ctulqprf2u595uto1p90f6l17n5gk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.butlr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqfp6Ad-__2qUnAmlVGs-nhs-WL-CfdG0',
    appId: '1:928726006564:ios:960bfcebeb26567a8411b1',
    messagingSenderId: '928726006564',
    projectId: 'crud-hr08',
    storageBucket: 'crud-hr08.appspot.com',
    androidClientId: '928726006564-9cl951lcbtrh3fa9vkne46gmbm6cvv5o.apps.googleusercontent.com',
    iosClientId: '928726006564-53ctulqprf2u595uto1p90f6l17n5gk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.butlr',
  );
}
